<?php

namespace Spinen\ConnectWise\Models\System;

use Spinen\ConnectWise\Support\Model;

class Member extends Model
{
    /**
     * Properties that need to be casts to a specific object or type
     *
     * @var array
     */
    protected $casts = [
        'adminFlag'                                => 'boolean',
        'allowExpensesEnteredAgainstCompaniesFlag' => 'boolean',
        'allowInCellEntryOnTimeSheet'              => 'boolean',
        'billableForecast'                         => 'double',
        //        'calendar'                                 => 'CalendarReference',
        'calendarSyncIntegrationFlag'              => 'boolean',
        //        'country'                                  => 'CountryReference',
        'dailyCapacity'                            => 'double',
        'daysTolerance'                            => 'integer',
        'defaultDepartmentId'                      => 'integer',
        //        'defaultEmail'                             => 'Enum',
        'defaultLocationId'                        => 'integer',
        //        'defaultPhone'                             => 'Enum',
        'disableOnlineFlag '                       => 'boolean',
        'enableLdapAuthenticationFlag'             => 'boolean',
        'enableMobileFlag '                        => 'boolean',
        'enableMobileGpsFlag '                     => 'boolean',
        'enterTimeAgainstCompanyFlag'              => 'boolean',
        //        'expenseApprover'                          => 'MemberReference',
        'firstName'                                => 'string',
        'hideMemberInDispatchPortalFlag'           => 'boolean',
        'hireDate'                                 => 'carbon',
        'homeEmail'                                => 'string',
        'homeExtension'                            => 'string',
        'homePhone'                                => 'string',
        'hourlyCost'                               => 'double',
        'hourlyRate'                               => 'double',
        'id'                                       => 'integer',
        'identifier'                               => 'string',
        'inactiveDate'                             => 'carbon',
        'inactiveFlag'                             => 'boolean',
        'includeInUtilizationReportingFlag'        => 'boolean',
        'lastLogin '                               => 'carbon',
        'lastName'                                 => 'string',
        //        'licenseClass'                             => 'Enum',
        'mapiName'                                 => 'string',
        'middleInitial'                            => 'string',
        'minimumHours'                             => 'double',
        'mobileEmail'                              => 'string',
        'mobileExtension'                          => 'string',
        'mobilePhone'                              => 'string',
        'notes'                                    => 'string',
        'officeEmail'                              => 'string',
        'officeExtension'                          => 'string',
        'officePhone'                              => 'string',
        //        'projectDefaultBoard'                      => 'ProjectBoardReference',
        'projectDefaultDepartmentId'               => 'integer',
        'projectDefaultLocationId'                 => 'integer',
        //        'reportsTo'                                => 'MemberReference',
        'requireExpenseEntryFlag'                  => 'boolean',
        'requireStartAndEndTimeOnTimeEntryFlag'    => 'boolean',
        'requireTimeSheetEntryFlag'                => 'boolean',
        'restrictDefaultSalesTerritoryFlag'        => 'boolean',
        'restrictDefaultWarehouseBinFlag'          => 'boolean',
        'restrictDefaultWarehouseFlag'             => 'boolean',
        'restrictDepartmentFlag'                   => 'boolean',
        'restrictLocationFlag'                     => 'boolean',
        'restrictProjectDefaultDepartmentFlag'     => 'boolean',
        'restrictProjectDefaultLocationFlag'       => 'boolean',
        'restrictScheduleFlag'                     => 'boolean',
        'restrictServiceDefaultDepartmentFlag'     => 'boolean',
        'restrictServiceDefaultLocationFlag'       => 'boolean',
        'salesDefaultLocationId'                   => 'integer',
        'scheduleCapacity'                         => 'double',
        'scheduleDefaultDepartmentId'              => 'integer',
        'scheduleDefaultLocationId'                => 'integer',
        'securityLevel '                           => 'string',
        'securityLocationId '                      => 'integer',
        //        'securityRole '                            => 'SecurityRoleReference',
        //        'serviceDefaultBoard'                      => 'BoardReference',
        'serviceDefaultDepartmentId'               => 'integer',
        'serviceDefaultLocationId'                 => 'integer',
        //        'serviceLocation'                          => 'ServiceLocationReference',
        //        'serviceTeams'                             => 'integer[]',
        //        'timeApprover'                             => 'MemberReference',
        'timeReminderEmailFlag'                    => 'boolean',
        'timeSheetStartDate'                       => 'carbon',
        //        'timeZone'                                 => 'TimeZoneReference',
        'title'                                    => 'string',
        //        'type'                                     => 'MemberTypeReference',
        'vendorNumber'                             => 'string',
        //        'warehouse'                                => 'WarehouseReference',
        //        'warehouseBin'                             => 'WarehouseBinReference',
        //        'workRole'                                 => 'WorkRoleReference',
        //        'workType'                                 => 'WorkTypeReference',
        //        '_info '                                   => 'Metadata',
        'System_Flag'                              => 'boolean',
    ];
}
