<?php

namespace Spinen\ConnectWise\Models\Finance;

use Spinen\ConnectWise\Support\Model;

class Agreement extends Model
{
    /**
     * Properties that need to be casts to a specific object or type
     *
     * @var array
     */
    protected $casts = [
        'id'                       => 'integer',
        'name'                     => 'string',
        //        'type'                     => 'AgreementTypeReference',
        //        'company'                  => 'CompanyReference',
        //        'contact'                  => 'ContactReference',
        //        'subContractCompany'       => 'CompanyReference',
        //        'subContractContact'       => 'ContactReference',
        'parentAgreementId'        => 'integer',
        'customerPO'               => 'string',
        'locationId'               => 'integer',
        'businessUnitId'           => 'integer',
        'restrictLocationFlag'     => 'boolean',
        'restrictDepartmentFlag'   => 'boolean',
        'startDate'                => 'carbon',
        'endDate'                  => 'string',
        'noEndingDateFlag'         => 'boolean',
        //        'opportunity'              => 'OpportunityReference',
        'cancelledFlag'            => 'boolean',
        'dateCancelled'            => 'carbon',
        'reasonCancelled'          => 'string',
        'slaId'                    => 'integer',
        'workOrder'                => 'string',
        'internalNotes'            => 'string',
        //        'applicationUnits'         => 'Enum',
        'applicationLimit'         => 'double',
        //        'applicationCycle'         => 'Enum',
        'applicationUnlimitedFlag' => 'boolean',
        'oneTimeFlag'              => 'boolean',
        'coverAgreementTime'       => 'boolean',
        'coverAgreementProduct'    => 'boolean',
        'coverAgreementExpense'    => 'boolean',
        'coverSalesTax'            => 'boolean',
        'carryOverUnused'          => 'boolean',
        'allowOverruns'            => 'boolean',
        'expiredDays'              => 'integer',
        'limit'                    => 'integer',
        'expireWhenZero'           => 'boolean',
        'chargeToFirm'             => 'boolean',
        //        'employeeCompRate'         => 'Enum',
        //        'employeeCompNotExceed'    => 'Enum',
        'compHourlyRate'           => 'double',
        'compLimitAmount'          => 'double',
        'billCycleId'              => 'integer',
        'billOneTimeFlag'          => 'boolean',
        'billTermsId'              => 'integer',
        //        'invoicingCycle'           => 'Enum',
        //        'billToCompany'            => 'CompanyReference',
        //        'billToSite'               => 'SiteReference',
        'billAmount'               => 'double',
        'taxable'                  => 'boolean',
        'prorateFirstBill'         => 'double',
        'billStartDate'            => 'carbon',
        'taxCodeId'                => 'integer',
        'restrictDownPayment'      => 'boolean',
        'invoiceDescription'       => 'string',
        'topComment'               => 'boolean',
        'bottomComment'            => 'boolean',
        //        'workRole'                 => 'WorkRoleReference',
        //        'workType'                 => 'WorkTypeReference',
        'projectTypeId'            => 'integer',
        'invoiceTemplateSetupId'   => 'integer',
        //        'billTime'                 => 'Enum',
        //        'billExpenses'             => 'Enum',
        //        'billProducts'             => 'Enum',
        'billableTimeInvoice'      => 'boolean',
        'billableExpenseInvoice'   => 'boolean',
        'billableProductInvoice'   => 'boolean',
        //        '_info'                    => 'Metadata',
        //        'periodType'               => 'Enum',
    ];
}
